version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: roomate_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        ports:
            - "5173:5173"
            - "6001:6001"

    nginx:
        image: nginx:latest
        container_name: roomate_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: roomate_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: roomate_db
            MYSQL_USER: roomate_user
            MYSQL_PASSWORD: roomate_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: roomate_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8081:80"

volumes:
    mysql_data:
